import type { ExerciseDefinition } from './types';

/** The five MVP exercises (spec §11). Data only — detection profiles arrive in Phase 3. */
export const EXERCISE_DEFINITIONS: readonly ExerciseDefinition[] = [
  {
    id: 'pushup',
    name: 'Push-up',
    category: 'strength',
    type: 'repetition',
    muscleGroups: { primary: ['chest'], secondary: ['triceps', 'shoulders', 'core'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope', 'proximity'],
    fallbackSensors: ['orientation'],
    difficulty: 2,
    detectionProfile: 'pushup',
    progressionProfile: 'strength-reps',
    placement: 'floor-in-front',
  },
  {
    id: 'squat',
    name: 'Squat',
    category: 'strength',
    type: 'repetition',
    muscleGroups: { primary: ['quadriceps', 'glutes'], secondary: ['hamstrings', 'core'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope', 'orientation'],
    fallbackSensors: ['orientation'],
    difficulty: 1,
    detectionProfile: 'squat',
    progressionProfile: 'strength-reps',
    placement: 'pocket-or-thigh',
  },
  {
    id: 'situp',
    name: 'Sit-up',
    category: 'core',
    type: 'repetition',
    muscleGroups: { primary: ['abdominals'], secondary: ['hip-flexors'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope', 'orientation'],
    fallbackSensors: ['orientation'],
    difficulty: 2,
    detectionProfile: 'situp',
    progressionProfile: 'strength-reps',
    placement: 'chest-strap-or-hold',
  },
  {
    id: 'jumping-jack',
    name: 'Jumping Jack',
    category: 'cardio',
    type: 'cyclic',
    muscleGroups: { primary: ['full-body'], secondary: ['calves', 'shoulders'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope', 'orientation'],
    fallbackSensors: ['orientation'],
    difficulty: 1,
    detectionProfile: 'jumping-jack',
    progressionProfile: 'cardio-reps',
    placement: 'pocket-or-armband',
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    type: 'duration',
    muscleGroups: { primary: ['core'], secondary: ['shoulders', 'glutes'] },
    requiredSensors: ['orientation'],
    preferredSensors: ['gyroscope', 'orientation'],
    fallbackSensors: ['accelerometer'],
    difficulty: 2,
    detectionProfile: 'plank',
    progressionProfile: 'duration-hold',
    placement: 'on-back-or-hold',
  },
];

export function getExerciseById(id: string): ExerciseDefinition | undefined {
  return EXERCISE_DEFINITIONS.find((e) => e.id === id);
}
