import type { ExerciseDefinition } from './types';

/** The five MVP exercises (spec §11). Data only — detection profiles arrive in Phase 3. */
export const EXERCISE_DEFINITIONS: readonly ExerciseDefinition[] = [
  {
    id: 'pushup',
    name: 'Push-up',
    category: 'strength',
    type: 'repetition',
    muscleGroups: { primary: ['chest'], secondary: ['triceps', 'shoulders', 'core'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope', 'proximity'],
    fallbackSensors: ['orientation'],
    difficulty: 2,
    detectionProfile: 'pushup',
    progressionProfile: 'strength-reps',
    placement: 'floor-in-front',
  },
  {
    id: 'squat',
    name: 'Squat',
    category: 'strength',
    type: 'repetition',
    muscleGroups: { primary: ['quadriceps', 'glutes'], secondary: ['hamstrings', 'core'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope', 'orientation'],
    fallbackSensors: ['orientation'],
    difficulty: 1,
    detectionProfile: 'squat',
    progressionProfile: 'strength-reps',
    placement: 'pocket-or-thigh',
  },
  {
    id: 'situp',
    name: 'Sit-up',
    category: 'core',
    type: 'repetition',
    muscleGroups: { primary: ['abdominals'], secondary: ['hip-flexors'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope', 'orientation'],
    fallbackSensors: ['orientation'],
    difficulty: 2,
    detectionProfile: 'situp',
    progressionProfile: 'strength-reps',
    placement: 'chest-strap-or-hold',
  },
  {
    id: 'jumping-jack',
    name: 'Jumping Jack',
    category: 'cardio',
    type: 'cyclic',
    muscleGroups: { primary: ['full-body'], secondary: ['calves', 'shoulders'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope', 'orientation'],
    fallbackSensors: ['orientation'],
    difficulty: 1,
    detectionProfile: 'jumping-jack',
    progressionProfile: 'cardio-reps',
    placement: 'pocket-or-armband',
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    type: 'duration',
    muscleGroups: { primary: ['core'], secondary: ['shoulders', 'glutes'] },
    requiredSensors: ['orientation'],
    preferredSensors: ['gyroscope', 'orientation'],
    fallbackSensors: ['accelerometer'],
    difficulty: 2,
    detectionProfile: 'plank',
    progressionProfile: 'duration-hold',
    placement: 'on-back-or-hold',
  },
  {
    id: 'crunch',
    name: 'Crunch',
    category: 'core',
    type: 'repetition',
    muscleGroups: { primary: ['abdominals'], secondary: ['obliques'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope', 'orientation'],
    fallbackSensors: ['orientation'],
    difficulty: 1,
    detectionProfile: 'crunch',
    progressionProfile: 'strength-reps',
    placement: 'chest-strap-or-hold',
  },
  {
    id: 'leg-raises',
    name: 'Leg Raises',
    category: 'core',
    type: 'repetition',
    muscleGroups: { primary: ['abdominals'], secondary: ['hip-flexors', 'quadriceps'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope', 'orientation'],
    fallbackSensors: ['orientation'],
    difficulty: 2,
    detectionProfile: 'leg-raises',
    progressionProfile: 'strength-reps',
    placement: 'pocket-or-thigh',
  },
  {
    id: 'leg-flutters',
    name: 'Leg Flutters',
    category: 'core',
    type: 'cyclic',
    muscleGroups: { primary: ['abdominals'], secondary: ['hip-flexors', 'quadriceps'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope'],
    fallbackSensors: ['orientation'],
    difficulty: 2,
    detectionProfile: 'leg-flutters',
    progressionProfile: 'cardio-reps',
    placement: 'pocket-or-thigh',
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    category: 'core',
    type: 'repetition',
    muscleGroups: { primary: ['obliques'], secondary: ['abdominals'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['gyroscope', 'orientation', 'accelerometer'],
    fallbackSensors: ['accelerometer'],
    difficulty: 2,
    detectionProfile: 'russian-twist',
    progressionProfile: 'strength-reps',
    placement: 'chest-strap-or-hold',
  },
  {
    id: 'high-knees',
    name: 'High Knees',
    category: 'cardio',
    type: 'cyclic',
    muscleGroups: { primary: ['quadriceps', 'core'], secondary: ['calves', 'hip-flexors'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope'],
    fallbackSensors: ['orientation'],
    difficulty: 2,
    detectionProfile: 'high-knees',
    progressionProfile: 'cardio-reps',
    placement: 'pocket-or-thigh',
  },
  {
    id: 'mountain-climbers',
    name: 'Mountain Climbers',
    category: 'cardio',
    type: 'cyclic',
    muscleGroups: { primary: ['core'], secondary: ['shoulders', 'quadriceps'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope'],
    fallbackSensors: ['orientation'],
    difficulty: 3,
    detectionProfile: 'mountain-climbers',
    progressionProfile: 'cardio-reps',
    placement: 'pocket-or-armband',
  },
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'cardio',
    type: 'repetition',
    muscleGroups: { primary: ['full-body'], secondary: ['chest', 'quadriceps', 'core'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope', 'orientation'],
    fallbackSensors: ['orientation'],
    difficulty: 4,
    detectionProfile: 'burpee',
    progressionProfile: 'cardio-reps',
    placement: 'pocket-or-armband',
  },
  {
    id: 'pull-up',
    name: 'Pull-up',
    category: 'strength',
    type: 'repetition',
    muscleGroups: { primary: ['back', 'biceps'], secondary: ['shoulders', 'core'] },
    requiredSensors: ['accelerometer'],
    preferredSensors: ['accelerometer', 'gyroscope'],
    fallbackSensors: ['orientation'],
    difficulty: 5,
    detectionProfile: 'pull-up',
    progressionProfile: 'strength-reps',
    placement: 'pocket-or-armband',
  },
];

export function getExerciseById(id: string): ExerciseDefinition | undefined {
  return EXERCISE_DEFINITIONS.find((e) => e.id === id);
}
